// flow-typed signature: 322f51c077c7376c898db5b3117fa251
// flow-typed version: <<STUB>>/base64-img_v^1.0.4/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-img'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-img' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base64-img/base64-img' {
  declare module.exports: any;
}

declare module 'base64-img/Gruntfile' {
  declare module.exports: any;
}

declare module 'base64-img/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base64-img/base64-img.js' {
  declare module.exports: $Exports<'base64-img/base64-img'>;
}
declare module 'base64-img/Gruntfile.js' {
  declare module.exports: $Exports<'base64-img/Gruntfile'>;
}
declare module 'base64-img/test/index' {
  declare module.exports: $Exports<'base64-img/test'>;
}
declare module 'base64-img/test/index.js' {
  declare module.exports: $Exports<'base64-img/test'>;
}
